/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/catalog/movie-edition-kinds": {
    /** List movie edition kinds */
    get: operations["listMovieEditionKinds"];
    /** Create a new movie edition kind */
    post: operations["postMovieEditionKind"];
  };
  "/catalog/movie-edition-kinds/{id}": {
    /** Get a movie edition kind by ID */
    get: operations["getMovieEditionKind"];
    /** Delete a movie edition kind */
    delete: operations["deleteMovieEditionKind"];
    /** Update a movie edition kind */
    patch: operations["patchMovieEditionKind"];
  };
  "/catalog/cards": {
    /** List cards */
    get: operations["listCards"];
    /** Create a new card */
    post: operations["postCard"];
  };
  "/catalog/cards/{id}": {
    /** Get a card by ID */
    get: operations["getCard"];
    /** Delete a card */
    delete: operations["deleteCard"];
    /** Update a card */
    patch: operations["patchCard"];
  };
  "/inbox/dvds": {
    /** List DVDs that have not been ingested to the manager yet. */
    get: operations["listInboxDVDs"];
  };
  "/media": {
    /** List all media entries. */
    get: operations["listMedia"];
    /** Create a new media entry. */
    post: operations["postMedia"];
  };
  "/media/{id}": {
    /** Get a media entry by ID. */
    get: operations["getMedia"];
    /** Delete a media entry. */
    delete: operations["deleteMedia"];
    /** Update a media entry. */
    patch: operations["patchMedia"];
  };
  "/media_sets": {
    /** List all media sets. */
    get: operations["listMediaSets"];
    /** Create a new media set. */
    post: operations["postMediaSet"];
  };
  "/media_sets/{id}": {
    /** Get a media set by ID. */
    get: operations["getMediaSet"];
    /** Delete a media set. */
    delete: operations["deleteMediaSet"];
    /** Update a media set. */
    patch: operations["patchMediaSet"];
  };
  "/tmdb/movies": {
    /** Search for movies in TMDB. */
    get: operations["searchTmdbMovies"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      type: string;
      title: string;
      status: number;
      detail: string;
    };
    MovieEditionKind: {
      /** Format: uint32 */
      id: number;
      name: string;
      is_default: boolean;
    };
    MovieEditionKindPage: {
      movie_edition_kinds: components["schemas"]["MovieEditionKind"][];
      next_page_token?: string;
    };
    /** @description Patch object with only one field set per instance */
    MovieEditionKindPatch: {
      name?: string;
      is_default?: boolean;
    };
    MovieEditionKindPost: {
      name: string;
      is_default?: boolean;
    };
    MovieEdition: {
      /** Format: uint32 */
      movie_id: number;
      /** Format: uint32 */
      kind_id: number;
    };
    /** @description Patch object with only one field set per instance */
    MovieEditionPatch: {
      /** Format: uint32 */
      kind_id?: number;
    };
    MovieEditionPost: {
      /** Format: uint32 */
      movie_id: number;
      /** Format: uint32 */
      kind_id: number;
    };
    Movie: {
      /** Format: uint64 */
      tmdb_id?: number;
      fanart_id?: string;
      /** Format: uint32 */
      release_year?: number;
      edition_ids: number[];
    };
    /** @description Patch object with only one field set per instance */
    MoviePatch: {
      /** Format: uint64 */
      tmdb_id?: number;
      fanart_id?: string;
      /** Format: uint32 */
      release_year?: number;
    };
    MoviePost: {
      /** Format: uint64 */
      tmdb_id?: number;
    };
    Card: {
      /** Format: uint32 */
      id: number;
      name: string;
      details: components["schemas"]["CardDetails"];
      note?: string;
    };
    /** @description Details of the card.  Only one field should be set. */
    CardDetails: {
      movie?: components["schemas"]["Movie"];
      movie_edition?: components["schemas"]["MovieEdition"];
    };
    CardPage: {
      cards: components["schemas"]["Card"][];
      next_page_token?: string;
    };
    /** @description Patch object with only one field set per instance */
    CardPatch: {
      name?: string;
      note?: string;
      movie?: components["schemas"]["MoviePatch"];
      movie_edition?: components["schemas"]["MovieEditionPatch"];
    };
    /** @description Request body for creating a card. */
    CardPost: {
      name: string;
      note?: string;
      details: components["schemas"]["CardPostDetails"];
      media_ids?: number[];
      media_set_ids?: number[];
    };
    /** @description Details of the created card.  Only one field should be set. */
    CardPostDetails: {
      movie?: components["schemas"]["Movie"];
      movie_edition?: components["schemas"]["MovieEdition"];
    };
    InboxPage: {
      paths: string[];
      next_page_token?: string;
    };
    Media: {
      /** Format: uint32 */
      id: number;
      details?: components["schemas"]["MediaDetails"];
      note?: string;
      /** Format: uint32 */
      media_set_id?: number;
      card_ids: number[];
    };
    /** @description Details of the media.  Only one field should be set. */
    MediaDetails: {
      dvd?: components["schemas"]["DVD"];
    };
    MediaPage: {
      media: components["schemas"]["Media"][];
      next_page_token?: string;
    };
    /** @description Patch object with only one field set per instance */
    MediaPatch: {
      name?: string;
      note?: string;
      /** Format: uint32 */
      media_set_id?: number;
      clear_media_set_id?: boolean;
      /** Format: uint32 */
      add_card_id?: number;
      /** Format: uint32 */
      remove_card_id?: number;
      dvd?: components["schemas"]["DVDPatch"];
    };
    /** @description Request body for creating a media entry. */
    MediaPost: {
      name: string;
      note?: string;
      details: components["schemas"]["MediaPostDetails"];
      /** Format: uint32 */
      media_set_id?: number;
      card_ids?: number[];
    };
    /** @description Details for creating a media entry.  Only one field should be set. */
    MediaPostDetails: {
      dvd_inbox_path?: string;
    };
    DVDIngestion: {
      /**
       * @description Ingestion state of the DVD.
       * @enum {string}
       */
      state: "pending" | "done" | "error";
      /** @description Error message.  Set if and only if state is 'error'. */
      error_message?: string;
    };
    DVD: {
      path: string;
      ingestion: components["schemas"]["DVDIngestion"];
    };
    /** @description Patch object with only one field set per instance */
    DVDPatch: {
      path?: string;
      ingestion?: components["schemas"]["DVDIngestion"];
    };
    MediaSet: {
      /** Format: uint32 */
      id: number;
      name: string;
      note?: string;
      card_ids: number[];
    };
    MediaSetPage: {
      media_sets: components["schemas"]["MediaSet"][];
      next_page_token?: string;
    };
    /** @description Patch object with only one field set per instance */
    MediaSetPatch: {
      name?: string;
      note?: string;
      clear_note?: boolean;
      /** Format: uint32 */
      add_card_id?: number;
      /** Format: uint32 */
      remove_card_id?: number;
      /** Format: uint32 */
      add_media_id?: number;
      /** Format: uint32 */
      remove_media_id?: number;
    };
    MediaSetPost: {
      name: string;
      note?: string;
      card_ids?: number[];
    };
    TmdbMovie: {
      /** Format: uint64 */
      tmdb_id: number;
      title: string;
      description?: string;
      /** Format: uint32 */
      release_year?: number;
      poster_url?: string;
    };
    TmdbMoviePage: {
      movies: components["schemas"]["TmdbMovie"][];
      next_page_token?: string;
    };
  };
  responses: {
    /** @description RFC 7807 compliant error response */
    ErrorResponse: {
      content: {
        "application/problem+json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** List movie edition kinds */
  listMovieEditionKinds: {
    parameters: {
      query?: {
        /** @description Maximum number of items to return */
        page_size?: number;
        /** @description Token for pagination */
        page_token?: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MovieEditionKindPage"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Create a new movie edition kind */
  postMovieEditionKind: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MovieEditionKindPost"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["MovieEditionKind"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Get a movie edition kind by ID */
  getMovieEditionKind: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MovieEditionKind"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Delete a movie edition kind */
  deleteMovieEditionKind: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Deleted successfully */
      204: {
        content: never;
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Update a movie edition kind */
  patchMovieEditionKind: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MovieEditionKindPatch"][];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MovieEditionKind"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** List cards */
  listCards: {
    parameters: {
      query?: {
        /** @description Maximum number of items to return */
        page_size?: number;
        /** @description Token for pagination */
        page_token?: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["CardPage"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Create a new card */
  postCard: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CardPost"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Get a card by ID */
  getCard: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Delete a card */
  deleteCard: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Deleted successfully */
      204: {
        content: never;
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Update a card */
  patchCard: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CardPatch"][];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** List DVDs that have not been ingested to the manager yet. */
  listInboxDVDs: {
    parameters: {
      query?: {
        /** @description Maximum number of items to return */
        page_size?: number;
        /** @description Token for pagination */
        page_token?: string;
      };
    };
    responses: {
      /** @description Successful response.  Returns paths of DVDs in the inbox. */
      200: {
        content: {
          "application/json": components["schemas"]["InboxPage"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** List all media entries. */
  listMedia: {
    parameters: {
      query?: {
        /** @description Maximum number of items to return */
        page_size?: number;
        /** @description Token for pagination */
        page_token?: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaPage"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Create a new media entry. */
  postMedia: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MediaPost"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Media"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Get a media entry by ID. */
  getMedia: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["Media"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Delete a media entry. */
  deleteMedia: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Deleted successfully */
      204: {
        content: never;
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Update a media entry. */
  patchMedia: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MediaPatch"][];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["Media"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** List all media sets. */
  listMediaSets: {
    parameters: {
      query?: {
        /** @description Maximum number of items to return */
        page_size?: number;
        /** @description Token for pagination */
        page_token?: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaSetPage"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Create a new media set. */
  postMediaSet: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MediaSetPost"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["MediaSet"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Get a media set by ID. */
  getMediaSet: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaSet"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Delete a media set. */
  deleteMediaSet: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Deleted successfully */
      204: {
        content: never;
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Update a media set. */
  patchMediaSet: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MediaSetPatch"][];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaSet"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Search for movies in TMDB. */
  searchTmdbMovies: {
    parameters: {
      query: {
        /** @description Search query string */
        query: string;
        /** @description Maximum number of items to return */
        page_size?: number;
        /** @description Token for pagination */
        page_token?: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["TmdbMoviePage"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
}
