/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/catalog/movie-edition-kinds": {
    /** List movie edition kinds */
    get: operations["listMovieEditionKinds"];
    /** Create a new movie edition kind */
    post: operations["postMovieEditionKind"];
  };
  "/catalog/movie-edition-kinds/{id}": {
    /** Get a movie edition kind by ID */
    get: operations["getMovieEditionKind"];
    /** Delete a movie edition kind */
    delete: operations["deleteMovieEditionKind"];
    /** Update a movie edition kind */
    patch: operations["patchMovieEditionKind"];
  };
  "/catalog/cards": {
    /** List cards */
    get: operations["listCards"];
    /** Create a new card */
    post: operations["postCard"];
  };
  "/catalog/cards/{id}": {
    /** Get a card by ID */
    get: operations["getCard"];
    /** Delete a card */
    delete: operations["deleteCard"];
    /** Update a card */
    patch: operations["patchCard"];
  };
  "/inbox/dvds": {
    /** List DVDs that have not been ingested to the manager yet. */
    get: operations["listInboxDVDs"];
  };
  "/media": {
    /** List all media entries. */
    get: operations["listMedia"];
    /** Create a new media entry. */
    post: operations["postMedia"];
  };
  "/media/{id}": {
    /** Get a media entry by ID. */
    get: operations["getMedia"];
    /** Delete a media entry. */
    delete: operations["deleteMedia"];
    /** Update a media entry. */
    patch: operations["patchMedia"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      message: string;
    };
    MovieEditionKind: {
      /** Format: uint32 */
      id: number;
      name: string;
      is_default: boolean;
    };
    MovieEditionKindPage: {
      movie_edition_kinds: components["schemas"]["MovieEditionKind"][];
      next_page_token?: string;
    };
    /** @description Patch object with only one field set per instance */
    MovieEditionKindPatch: {
      name?: string;
      is_default?: boolean;
    };
    MovieEdition: {
      /** Format: uint32 */
      id: number;
      kind: components["schemas"]["MovieEditionKind"];
    };
    Movie: {
      /** Format: uint32 */
      id: number;
      /** Format: uint64 */
      tmdb_id?: number;
      fanart_id?: string;
      editions: components["schemas"]["MovieEdition"][];
    };
    /** @description Patch object with only one field set per instance */
    MoviePatch: {
      /** Format: uint64 */
      tmdb_id?: number;
      fanart_id?: string;
      /** Format: uint32 */
      add_movie_edition_kind_id?: number;
      /** Format: uint32 */
      remove_movie_edition_id?: number;
    };
    Card: {
      /** Format: uint32 */
      id: number;
      name: string;
      /** Format: uint32 */
      year?: number;
      movie?: components["schemas"]["Movie"];
    };
    CardPage: {
      cards: components["schemas"]["Card"][];
      next_page_token?: string;
    };
    /** @description Patch object with only one field set per instance */
    CardPatch: {
      name?: string;
      /** Format: uint32 */
      year?: number;
      movie?: components["schemas"]["MoviePatch"];
    };
    /** @description Data source for creating a movie.  Only one field should be set. */
    MoviePostDataSource: {
      /** Format: uint64 */
      tmdb_movie_id?: number;
    };
    MoviePost: {
      data_source: components["schemas"]["MoviePostDataSource"];
      movie_edition_kind_ids?: number[];
    };
    InboxPage: {
      paths: string[];
      next_page_token?: string;
    };
    Media: {
      /** Format: uint32 */
      id: number;
      /** Format: uint32 */
      media_set_id?: number;
      cards_ids: number[];
      dvd?: components["schemas"]["DVD"];
    };
    /** @description Patch object with only one field set per instance */
    MediaPatch: {
      /** Format: uint32 */
      media_set_id?: number;
      /** Format: uint32 */
      add_card_id?: number;
      /** Format: uint32 */
      remove_card_id?: number;
      dvd?: components["schemas"]["DVDPatch"];
    };
    MediaPage: {
      media: components["schemas"]["Media"][];
      next_page_token?: string;
    };
    /** @description Request body for creating a media entry. */
    MediaPost: {
      /** Format: uint32 */
      media_set_id?: number;
      card_ids?: number[];
      data_source: components["schemas"]["MediaPostDataSource"];
    };
    /** @description Data source for creating a media entry.  Only one field should be set. */
    MediaPostDataSource: {
      dvd_path?: string;
    };
    /** @enum {string} */
    DVDIngestionState: "pending" | "done" | "error";
    DVD: {
      path: string;
      ingestion_state: components["schemas"]["DVDIngestionState"];
      ingestion_error?: string;
    };
    /** @description Patch object with only one field set per instance */
    DVDPatch: {
      path?: string;
      ingestion_state?: components["schemas"]["DVDIngestionState"];
      ingestion_error?: string;
    };
    MediaSet: {
      /** Format: uint32 */
      id: number;
      name: string;
      cards_ids: number[];
    };
    /** @description Patch object with only one field set per instance */
    MediaSetPatch: {
      name?: string;
      /** Format: uint32 */
      add_card_id?: number;
      /** Format: uint32 */
      remove_card_id?: number;
    };
    MediaSetPage: {
      media_sets: components["schemas"]["MediaSet"][];
      next_page_token?: string;
    };
  };
  responses: {
    /** @description Error response */
    ErrorResponse: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** List movie edition kinds */
  listMovieEditionKinds: {
    parameters: {
      query?: {
        /** @description Maximum number of items to return */
        page_size?: number;
        /** @description Token for pagination */
        page_token?: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MovieEditionKindPage"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Create a new movie edition kind */
  postMovieEditionKind: {
    requestBody: {
      content: {
        "application/json": {
          name: string;
          is_default?: boolean;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["MovieEditionKind"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Get a movie edition kind by ID */
  getMovieEditionKind: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MovieEditionKind"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Delete a movie edition kind */
  deleteMovieEditionKind: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Deleted successfully */
      204: {
        content: never;
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Update a movie edition kind */
  patchMovieEditionKind: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MovieEditionKindPatch"][];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MovieEditionKind"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** List cards */
  listCards: {
    parameters: {
      query?: {
        /** @description Maximum number of items to return */
        page_size?: number;
        /** @description Token for pagination */
        page_token?: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["CardPage"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Create a new card */
  postCard: {
    requestBody: {
      content: {
        "application/json": {
          movie?: components["schemas"]["MoviePost"];
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Get a card by ID */
  getCard: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Delete a card */
  deleteCard: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Deleted successfully */
      204: {
        content: never;
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Update a card */
  patchCard: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CardPatch"][];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** List DVDs that have not been ingested to the manager yet. */
  listInboxDVDs: {
    parameters: {
      query?: {
        /** @description Maximum number of items to return */
        page_size?: number;
        /** @description Token for pagination */
        page_token?: string;
      };
    };
    responses: {
      /** @description Successful response.  Returns paths of DVDs in the inbox. */
      200: {
        content: {
          "application/json": components["schemas"]["InboxPage"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** List all media entries. */
  listMedia: {
    parameters: {
      query?: {
        /** @description Maximum number of items to return */
        page_size?: number;
        /** @description Token for pagination */
        page_token?: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaPage"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Create a new media entry. */
  postMedia: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MediaPost"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Media"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Get a media entry by ID. */
  getMedia: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["Media"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Delete a media entry. */
  deleteMedia: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Deleted successfully */
      204: {
        content: never;
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Update a media entry. */
  patchMedia: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MediaPatch"][];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["Media"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
}
