/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/catalog/movie-edition-kinds": {
    /** List movie edition kinds */
    get: operations["listMovieEditionKinds"];
    /** Create a new movie edition kind */
    post: operations["postMovieEditionKind"];
  };
  "/catalog/movie-edition-kinds/{id}": {
    /** Get a movie edition kind by ID */
    get: operations["getMovieEditionKind"];
    /** Delete a movie edition kind */
    delete: operations["deleteMovieEditionKind"];
    /** Update a movie edition kind */
    patch: operations["patchMovieEditionKind"];
  };
  "/catalog/cards": {
    /** List cards */
    get: operations["listCards"];
    /** Create a new card */
    post: operations["postCard"];
  };
  "/catalog/cards/{id}": {
    /** Get a card by ID */
    get: operations["getCard"];
    /** Delete a card */
    delete: operations["deleteCard"];
    /** Update a card */
    patch: operations["patchCard"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      message: string;
    };
    MovieEditionKind: {
      /** Format: uint32 */
      id: number;
      name: string;
      is_default: boolean;
    };
    /** @description Patch object with only one field set per instance */
    MovieEditionKindPatch: {
      name?: string;
      is_default?: boolean;
    };
    MovieEdition: {
      /** Format: uint32 */
      id: number;
      kind: components["schemas"]["MovieEditionKind"];
    };
    Movie: {
      /** Format: uint32 */
      id: number;
      /** Format: uint64 */
      tmdb_id?: number;
      fanart_id?: string;
      editions: components["schemas"]["MovieEdition"][];
    };
    /** @description Patch object with only one field set per instance */
    MoviePatch: {
      /** Format: uint64 */
      tmdb_id?: number;
      fanart_id?: string;
      /** Format: uint32 */
      add_movie_edition_kind_id?: number;
      /** Format: uint32 */
      remove_movie_edition_id?: number;
    };
    Card: {
      /** Format: uint32 */
      id: number;
      name: string;
      /** Format: uint32 */
      year?: number;
      movie?: components["schemas"]["Movie"];
    };
    /** @description Patch object with only one field set per instance */
    CardPatch: {
      name?: string;
      /** Format: uint32 */
      year?: number;
      movie?: components["schemas"]["MoviePatch"];
    };
    /** @description Data source for creating a movie.  Only one field should be set. */
    MoviePostDataSource: {
      /** Format: uint64 */
      tmdb_movie_id?: number;
    };
    MoviePost: {
      data_source: components["schemas"]["MoviePostDataSource"];
      movie_edition_kind_ids?: number[];
    };
  };
  responses: {
    /** @description Error response */
    ErrorResponse: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** List movie edition kinds */
  listMovieEditionKinds: {
    parameters: {
      query?: {
        /** @description Maximum number of items to return */
        page_size?: number;
        /** @description Token for pagination */
        page_token?: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": {
            movie_edition_kinds: components["schemas"]["MovieEditionKind"][];
            next_page_token?: string;
          };
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Create a new movie edition kind */
  postMovieEditionKind: {
    requestBody: {
      content: {
        "application/json": {
          name: string;
          is_default?: boolean;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["MovieEditionKind"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Get a movie edition kind by ID */
  getMovieEditionKind: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MovieEditionKind"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Delete a movie edition kind */
  deleteMovieEditionKind: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Deleted successfully */
      204: {
        content: never;
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Update a movie edition kind */
  patchMovieEditionKind: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MovieEditionKindPatch"][];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["MovieEditionKind"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** List cards */
  listCards: {
    parameters: {
      query?: {
        /** @description Maximum number of items to return */
        page_size?: number;
        /** @description Token for pagination */
        page_token?: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": {
            cards: components["schemas"]["Card"][];
            next_page_token?: string;
          };
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Create a new card */
  postCard: {
    requestBody: {
      content: {
        "application/json": {
          movie?: components["schemas"]["MoviePost"];
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Get a card by ID */
  getCard: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Delete a card */
  deleteCard: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Deleted successfully */
      204: {
        content: never;
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
  /** Update a card */
  patchCard: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CardPatch"][];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
      default: components["responses"]["ErrorResponse"];
    };
  };
}
