//go:build go1.22

// Package vmapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package vmapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Card defines model for Card.
type Card struct {
	Id    uint32  `json:"id"`
	Movie *Movie  `json:"movie,omitempty"`
	Name  string  `json:"name"`
	Year  *uint32 `json:"year,omitempty"`
}

// CardPage defines model for CardPage.
type CardPage struct {
	Cards         []Card  `json:"cards"`
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// CardPatch Patch object with only one field set per instance
type CardPatch struct {
	// Movie Patch object with only one field set per instance
	Movie *MoviePatch `json:"movie,omitempty"`
	Name  *string     `json:"name,omitempty"`
	Year  *uint32     `json:"year,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// InboxPage defines model for InboxPage.
type InboxPage struct {
	NextPageToken *string  `json:"next_page_token,omitempty"`
	Paths         []string `json:"paths"`
}

// Movie defines model for Movie.
type Movie struct {
	Editions []MovieEdition `json:"editions"`
	FanartId *string        `json:"fanart_id,omitempty"`
	Id       uint32         `json:"id"`
	TmdbId   *uint64        `json:"tmdb_id,omitempty"`
}

// MovieEdition defines model for MovieEdition.
type MovieEdition struct {
	Id   uint32           `json:"id"`
	Kind MovieEditionKind `json:"kind"`
}

// MovieEditionKind defines model for MovieEditionKind.
type MovieEditionKind struct {
	Id        uint32 `json:"id"`
	IsDefault bool   `json:"is_default"`
	Name      string `json:"name"`
}

// MovieEditionKindPage defines model for MovieEditionKindPage.
type MovieEditionKindPage struct {
	MovieEditionKinds []MovieEditionKind `json:"movie_edition_kinds"`
	NextPageToken     *string            `json:"next_page_token,omitempty"`
}

// MovieEditionKindPatch Patch object with only one field set per instance
type MovieEditionKindPatch struct {
	IsDefault *bool   `json:"is_default,omitempty"`
	Name      *string `json:"name,omitempty"`
}

// MoviePatch Patch object with only one field set per instance
type MoviePatch struct {
	AddMovieEditionKindId *uint32 `json:"add_movie_edition_kind_id,omitempty"`
	FanartId              *string `json:"fanart_id,omitempty"`
	RemoveMovieEditionId  *uint32 `json:"remove_movie_edition_id,omitempty"`
	TmdbId                *uint64 `json:"tmdb_id,omitempty"`
}

// MoviePost defines model for MoviePost.
type MoviePost struct {
	// DataSource Data source for creating a movie.  Only one field should be set.
	DataSource          MoviePostDataSource `json:"data_source"`
	MovieEditionKindIds []uint32            `json:"movie_edition_kind_ids,omitempty"`
}

// MoviePostDataSource Data source for creating a movie.  Only one field should be set.
type MoviePostDataSource struct {
	TmdbMovieId *uint64 `json:"tmdb_movie_id,omitempty"`
}

// ListCardsParams defines parameters for ListCards.
type ListCardsParams struct {
	// PageSize Maximum number of items to return
	PageSize *uint32 `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// PostCardJSONBody defines parameters for PostCard.
type PostCardJSONBody struct {
	Movie *MoviePost `json:"movie,omitempty"`
}

// PatchCardJSONBody defines parameters for PatchCard.
type PatchCardJSONBody = []CardPatch

// ListMovieEditionKindsParams defines parameters for ListMovieEditionKinds.
type ListMovieEditionKindsParams struct {
	// PageSize Maximum number of items to return
	PageSize *uint32 `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// PostMovieEditionKindJSONBody defines parameters for PostMovieEditionKind.
type PostMovieEditionKindJSONBody struct {
	IsDefault *bool  `json:"is_default,omitempty"`
	Name      string `json:"name"`
}

// PatchMovieEditionKindJSONBody defines parameters for PatchMovieEditionKind.
type PatchMovieEditionKindJSONBody = []MovieEditionKindPatch

// GetInboxDVDsParams defines parameters for GetInboxDVDs.
type GetInboxDVDsParams struct {
	// PageSize Maximum number of items to return
	PageSize *uint32 `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// PostCardJSONRequestBody defines body for PostCard for application/json ContentType.
type PostCardJSONRequestBody PostCardJSONBody

// PatchCardJSONRequestBody defines body for PatchCard for application/json ContentType.
type PatchCardJSONRequestBody = PatchCardJSONBody

// PostMovieEditionKindJSONRequestBody defines body for PostMovieEditionKind for application/json ContentType.
type PostMovieEditionKindJSONRequestBody PostMovieEditionKindJSONBody

// PatchMovieEditionKindJSONRequestBody defines body for PatchMovieEditionKind for application/json ContentType.
type PatchMovieEditionKindJSONRequestBody = PatchMovieEditionKindJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListCards request
	ListCards(ctx context.Context, params *ListCardsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCardWithBody request with any body
	PostCardWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCard(ctx context.Context, body PostCardJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteCard request
	DeleteCard(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCard request
	GetCard(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchCardWithBody request with any body
	PatchCardWithBody(ctx context.Context, id uint32, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchCard(ctx context.Context, id uint32, body PatchCardJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListMovieEditionKinds request
	ListMovieEditionKinds(ctx context.Context, params *ListMovieEditionKindsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostMovieEditionKindWithBody request with any body
	PostMovieEditionKindWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostMovieEditionKind(ctx context.Context, body PostMovieEditionKindJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteMovieEditionKind request
	DeleteMovieEditionKind(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMovieEditionKind request
	GetMovieEditionKind(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchMovieEditionKindWithBody request with any body
	PatchMovieEditionKindWithBody(ctx context.Context, id uint32, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchMovieEditionKind(ctx context.Context, id uint32, body PatchMovieEditionKindJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetInboxDVDs request
	GetInboxDVDs(ctx context.Context, params *GetInboxDVDsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListCards(ctx context.Context, params *ListCardsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCardsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCardWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCardRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCard(ctx context.Context, body PostCardJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCardRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteCard(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteCardRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCard(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCardRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchCardWithBody(ctx context.Context, id uint32, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchCardRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchCard(ctx context.Context, id uint32, body PatchCardJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchCardRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListMovieEditionKinds(ctx context.Context, params *ListMovieEditionKindsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListMovieEditionKindsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostMovieEditionKindWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMovieEditionKindRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostMovieEditionKind(ctx context.Context, body PostMovieEditionKindJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMovieEditionKindRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteMovieEditionKind(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteMovieEditionKindRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMovieEditionKind(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMovieEditionKindRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchMovieEditionKindWithBody(ctx context.Context, id uint32, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchMovieEditionKindRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchMovieEditionKind(ctx context.Context, id uint32, body PatchMovieEditionKindJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchMovieEditionKindRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetInboxDVDs(ctx context.Context, params *GetInboxDVDsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetInboxDVDsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListCardsRequest generates requests for ListCards
func NewListCardsRequest(server string, params *ListCardsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalog/cards")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_size", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_token", runtime.ParamLocationQuery, *params.PageToken); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostCardRequest calls the generic PostCard builder with application/json body
func NewPostCardRequest(server string, body PostCardJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCardRequestWithBody(server, "application/json", bodyReader)
}

// NewPostCardRequestWithBody generates requests for PostCard with any type of body
func NewPostCardRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalog/cards")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteCardRequest generates requests for DeleteCard
func NewDeleteCardRequest(server string, id uint32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalog/cards/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCardRequest generates requests for GetCard
func NewGetCardRequest(server string, id uint32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalog/cards/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchCardRequest calls the generic PatchCard builder with application/json body
func NewPatchCardRequest(server string, id uint32, body PatchCardJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchCardRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPatchCardRequestWithBody generates requests for PatchCard with any type of body
func NewPatchCardRequestWithBody(server string, id uint32, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalog/cards/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListMovieEditionKindsRequest generates requests for ListMovieEditionKinds
func NewListMovieEditionKindsRequest(server string, params *ListMovieEditionKindsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalog/movie-edition-kinds")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_size", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_token", runtime.ParamLocationQuery, *params.PageToken); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostMovieEditionKindRequest calls the generic PostMovieEditionKind builder with application/json body
func NewPostMovieEditionKindRequest(server string, body PostMovieEditionKindJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostMovieEditionKindRequestWithBody(server, "application/json", bodyReader)
}

// NewPostMovieEditionKindRequestWithBody generates requests for PostMovieEditionKind with any type of body
func NewPostMovieEditionKindRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalog/movie-edition-kinds")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteMovieEditionKindRequest generates requests for DeleteMovieEditionKind
func NewDeleteMovieEditionKindRequest(server string, id uint32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalog/movie-edition-kinds/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMovieEditionKindRequest generates requests for GetMovieEditionKind
func NewGetMovieEditionKindRequest(server string, id uint32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalog/movie-edition-kinds/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchMovieEditionKindRequest calls the generic PatchMovieEditionKind builder with application/json body
func NewPatchMovieEditionKindRequest(server string, id uint32, body PatchMovieEditionKindJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchMovieEditionKindRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPatchMovieEditionKindRequestWithBody generates requests for PatchMovieEditionKind with any type of body
func NewPatchMovieEditionKindRequestWithBody(server string, id uint32, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalog/movie-edition-kinds/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetInboxDVDsRequest generates requests for GetInboxDVDs
func NewGetInboxDVDsRequest(server string, params *GetInboxDVDsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/inbox/dvd")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_size", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_token", runtime.ParamLocationQuery, *params.PageToken); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListCardsWithResponse request
	ListCardsWithResponse(ctx context.Context, params *ListCardsParams, reqEditors ...RequestEditorFn) (*ListCardsResponse, error)

	// PostCardWithBodyWithResponse request with any body
	PostCardWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCardResponse, error)

	PostCardWithResponse(ctx context.Context, body PostCardJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCardResponse, error)

	// DeleteCardWithResponse request
	DeleteCardWithResponse(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*DeleteCardResponse, error)

	// GetCardWithResponse request
	GetCardWithResponse(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*GetCardResponse, error)

	// PatchCardWithBodyWithResponse request with any body
	PatchCardWithBodyWithResponse(ctx context.Context, id uint32, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchCardResponse, error)

	PatchCardWithResponse(ctx context.Context, id uint32, body PatchCardJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchCardResponse, error)

	// ListMovieEditionKindsWithResponse request
	ListMovieEditionKindsWithResponse(ctx context.Context, params *ListMovieEditionKindsParams, reqEditors ...RequestEditorFn) (*ListMovieEditionKindsResponse, error)

	// PostMovieEditionKindWithBodyWithResponse request with any body
	PostMovieEditionKindWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMovieEditionKindResponse, error)

	PostMovieEditionKindWithResponse(ctx context.Context, body PostMovieEditionKindJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMovieEditionKindResponse, error)

	// DeleteMovieEditionKindWithResponse request
	DeleteMovieEditionKindWithResponse(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*DeleteMovieEditionKindResponse, error)

	// GetMovieEditionKindWithResponse request
	GetMovieEditionKindWithResponse(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*GetMovieEditionKindResponse, error)

	// PatchMovieEditionKindWithBodyWithResponse request with any body
	PatchMovieEditionKindWithBodyWithResponse(ctx context.Context, id uint32, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchMovieEditionKindResponse, error)

	PatchMovieEditionKindWithResponse(ctx context.Context, id uint32, body PatchMovieEditionKindJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchMovieEditionKindResponse, error)

	// GetInboxDVDsWithResponse request
	GetInboxDVDsWithResponse(ctx context.Context, params *GetInboxDVDsParams, reqEditors ...RequestEditorFn) (*GetInboxDVDsResponse, error)
}

type ListCardsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CardPage
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListCardsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCardsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostCardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Card
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostCardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteCardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteCardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteCardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Card
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetCardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchCardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Card
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PatchCardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchCardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListMovieEditionKindsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MovieEditionKindPage
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListMovieEditionKindsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListMovieEditionKindsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostMovieEditionKindResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *MovieEditionKind
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostMovieEditionKindResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostMovieEditionKindResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteMovieEditionKindResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteMovieEditionKindResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteMovieEditionKindResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMovieEditionKindResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MovieEditionKind
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetMovieEditionKindResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMovieEditionKindResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchMovieEditionKindResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MovieEditionKind
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PatchMovieEditionKindResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchMovieEditionKindResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetInboxDVDsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InboxPage
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetInboxDVDsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetInboxDVDsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListCardsWithResponse request returning *ListCardsResponse
func (c *ClientWithResponses) ListCardsWithResponse(ctx context.Context, params *ListCardsParams, reqEditors ...RequestEditorFn) (*ListCardsResponse, error) {
	rsp, err := c.ListCards(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCardsResponse(rsp)
}

// PostCardWithBodyWithResponse request with arbitrary body returning *PostCardResponse
func (c *ClientWithResponses) PostCardWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCardResponse, error) {
	rsp, err := c.PostCardWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCardResponse(rsp)
}

func (c *ClientWithResponses) PostCardWithResponse(ctx context.Context, body PostCardJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCardResponse, error) {
	rsp, err := c.PostCard(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCardResponse(rsp)
}

// DeleteCardWithResponse request returning *DeleteCardResponse
func (c *ClientWithResponses) DeleteCardWithResponse(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*DeleteCardResponse, error) {
	rsp, err := c.DeleteCard(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteCardResponse(rsp)
}

// GetCardWithResponse request returning *GetCardResponse
func (c *ClientWithResponses) GetCardWithResponse(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*GetCardResponse, error) {
	rsp, err := c.GetCard(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCardResponse(rsp)
}

// PatchCardWithBodyWithResponse request with arbitrary body returning *PatchCardResponse
func (c *ClientWithResponses) PatchCardWithBodyWithResponse(ctx context.Context, id uint32, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchCardResponse, error) {
	rsp, err := c.PatchCardWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchCardResponse(rsp)
}

func (c *ClientWithResponses) PatchCardWithResponse(ctx context.Context, id uint32, body PatchCardJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchCardResponse, error) {
	rsp, err := c.PatchCard(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchCardResponse(rsp)
}

// ListMovieEditionKindsWithResponse request returning *ListMovieEditionKindsResponse
func (c *ClientWithResponses) ListMovieEditionKindsWithResponse(ctx context.Context, params *ListMovieEditionKindsParams, reqEditors ...RequestEditorFn) (*ListMovieEditionKindsResponse, error) {
	rsp, err := c.ListMovieEditionKinds(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListMovieEditionKindsResponse(rsp)
}

// PostMovieEditionKindWithBodyWithResponse request with arbitrary body returning *PostMovieEditionKindResponse
func (c *ClientWithResponses) PostMovieEditionKindWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMovieEditionKindResponse, error) {
	rsp, err := c.PostMovieEditionKindWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMovieEditionKindResponse(rsp)
}

func (c *ClientWithResponses) PostMovieEditionKindWithResponse(ctx context.Context, body PostMovieEditionKindJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMovieEditionKindResponse, error) {
	rsp, err := c.PostMovieEditionKind(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMovieEditionKindResponse(rsp)
}

// DeleteMovieEditionKindWithResponse request returning *DeleteMovieEditionKindResponse
func (c *ClientWithResponses) DeleteMovieEditionKindWithResponse(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*DeleteMovieEditionKindResponse, error) {
	rsp, err := c.DeleteMovieEditionKind(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteMovieEditionKindResponse(rsp)
}

// GetMovieEditionKindWithResponse request returning *GetMovieEditionKindResponse
func (c *ClientWithResponses) GetMovieEditionKindWithResponse(ctx context.Context, id uint32, reqEditors ...RequestEditorFn) (*GetMovieEditionKindResponse, error) {
	rsp, err := c.GetMovieEditionKind(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMovieEditionKindResponse(rsp)
}

// PatchMovieEditionKindWithBodyWithResponse request with arbitrary body returning *PatchMovieEditionKindResponse
func (c *ClientWithResponses) PatchMovieEditionKindWithBodyWithResponse(ctx context.Context, id uint32, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchMovieEditionKindResponse, error) {
	rsp, err := c.PatchMovieEditionKindWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchMovieEditionKindResponse(rsp)
}

func (c *ClientWithResponses) PatchMovieEditionKindWithResponse(ctx context.Context, id uint32, body PatchMovieEditionKindJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchMovieEditionKindResponse, error) {
	rsp, err := c.PatchMovieEditionKind(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchMovieEditionKindResponse(rsp)
}

// GetInboxDVDsWithResponse request returning *GetInboxDVDsResponse
func (c *ClientWithResponses) GetInboxDVDsWithResponse(ctx context.Context, params *GetInboxDVDsParams, reqEditors ...RequestEditorFn) (*GetInboxDVDsResponse, error) {
	rsp, err := c.GetInboxDVDs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetInboxDVDsResponse(rsp)
}

// ParseListCardsResponse parses an HTTP response from a ListCardsWithResponse call
func ParseListCardsResponse(rsp *http.Response) (*ListCardsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCardsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CardPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePostCardResponse parses an HTTP response from a PostCardWithResponse call
func ParsePostCardResponse(rsp *http.Response) (*PostCardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Card
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteCardResponse parses an HTTP response from a DeleteCardWithResponse call
func ParseDeleteCardResponse(rsp *http.Response) (*DeleteCardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteCardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetCardResponse parses an HTTP response from a GetCardWithResponse call
func ParseGetCardResponse(rsp *http.Response) (*GetCardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Card
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePatchCardResponse parses an HTTP response from a PatchCardWithResponse call
func ParsePatchCardResponse(rsp *http.Response) (*PatchCardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchCardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Card
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseListMovieEditionKindsResponse parses an HTTP response from a ListMovieEditionKindsWithResponse call
func ParseListMovieEditionKindsResponse(rsp *http.Response) (*ListMovieEditionKindsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListMovieEditionKindsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MovieEditionKindPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePostMovieEditionKindResponse parses an HTTP response from a PostMovieEditionKindWithResponse call
func ParsePostMovieEditionKindResponse(rsp *http.Response) (*PostMovieEditionKindResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostMovieEditionKindResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest MovieEditionKind
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteMovieEditionKindResponse parses an HTTP response from a DeleteMovieEditionKindWithResponse call
func ParseDeleteMovieEditionKindResponse(rsp *http.Response) (*DeleteMovieEditionKindResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteMovieEditionKindResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetMovieEditionKindResponse parses an HTTP response from a GetMovieEditionKindWithResponse call
func ParseGetMovieEditionKindResponse(rsp *http.Response) (*GetMovieEditionKindResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMovieEditionKindResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MovieEditionKind
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePatchMovieEditionKindResponse parses an HTTP response from a PatchMovieEditionKindWithResponse call
func ParsePatchMovieEditionKindResponse(rsp *http.Response) (*PatchMovieEditionKindResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchMovieEditionKindResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MovieEditionKind
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetInboxDVDsResponse parses an HTTP response from a GetInboxDVDsWithResponse call
func ParseGetInboxDVDsResponse(rsp *http.Response) (*GetInboxDVDsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetInboxDVDsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InboxPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List cards
	// (GET /catalog/cards)
	ListCards(w http.ResponseWriter, r *http.Request, params ListCardsParams)
	// Create a new card
	// (POST /catalog/cards)
	PostCard(w http.ResponseWriter, r *http.Request)
	// Delete a card
	// (DELETE /catalog/cards/{id})
	DeleteCard(w http.ResponseWriter, r *http.Request, id uint32)
	// Get a card by ID
	// (GET /catalog/cards/{id})
	GetCard(w http.ResponseWriter, r *http.Request, id uint32)
	// Update a card
	// (PATCH /catalog/cards/{id})
	PatchCard(w http.ResponseWriter, r *http.Request, id uint32)
	// List movie edition kinds
	// (GET /catalog/movie-edition-kinds)
	ListMovieEditionKinds(w http.ResponseWriter, r *http.Request, params ListMovieEditionKindsParams)
	// Create a new movie edition kind
	// (POST /catalog/movie-edition-kinds)
	PostMovieEditionKind(w http.ResponseWriter, r *http.Request)
	// Delete a movie edition kind
	// (DELETE /catalog/movie-edition-kinds/{id})
	DeleteMovieEditionKind(w http.ResponseWriter, r *http.Request, id uint32)
	// Get a movie edition kind by ID
	// (GET /catalog/movie-edition-kinds/{id})
	GetMovieEditionKind(w http.ResponseWriter, r *http.Request, id uint32)
	// Update a movie edition kind
	// (PATCH /catalog/movie-edition-kinds/{id})
	PatchMovieEditionKind(w http.ResponseWriter, r *http.Request, id uint32)
	// Get DVDs that have not been ingested to the manager yet.
	// (GET /inbox/dvd)
	GetInboxDVDs(w http.ResponseWriter, r *http.Request, params GetInboxDVDsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCards operation middleware
func (siw *ServerInterfaceWrapper) ListCards(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCardsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCards(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCard operation middleware
func (siw *ServerInterfaceWrapper) PostCard(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCard operation middleware
func (siw *ServerInterfaceWrapper) DeleteCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id uint32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCard operation middleware
func (siw *ServerInterfaceWrapper) GetCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id uint32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchCard operation middleware
func (siw *ServerInterfaceWrapper) PatchCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id uint32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchCard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMovieEditionKinds operation middleware
func (siw *ServerInterfaceWrapper) ListMovieEditionKinds(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMovieEditionKindsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMovieEditionKinds(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMovieEditionKind operation middleware
func (siw *ServerInterfaceWrapper) PostMovieEditionKind(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMovieEditionKind(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMovieEditionKind operation middleware
func (siw *ServerInterfaceWrapper) DeleteMovieEditionKind(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id uint32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMovieEditionKind(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMovieEditionKind operation middleware
func (siw *ServerInterfaceWrapper) GetMovieEditionKind(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id uint32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMovieEditionKind(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchMovieEditionKind operation middleware
func (siw *ServerInterfaceWrapper) PatchMovieEditionKind(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id uint32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchMovieEditionKind(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInboxDVDs operation middleware
func (siw *ServerInterfaceWrapper) GetInboxDVDs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInboxDVDsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInboxDVDs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/catalog/cards", wrapper.ListCards)
	m.HandleFunc("POST "+options.BaseURL+"/catalog/cards", wrapper.PostCard)
	m.HandleFunc("DELETE "+options.BaseURL+"/catalog/cards/{id}", wrapper.DeleteCard)
	m.HandleFunc("GET "+options.BaseURL+"/catalog/cards/{id}", wrapper.GetCard)
	m.HandleFunc("PATCH "+options.BaseURL+"/catalog/cards/{id}", wrapper.PatchCard)
	m.HandleFunc("GET "+options.BaseURL+"/catalog/movie-edition-kinds", wrapper.ListMovieEditionKinds)
	m.HandleFunc("POST "+options.BaseURL+"/catalog/movie-edition-kinds", wrapper.PostMovieEditionKind)
	m.HandleFunc("DELETE "+options.BaseURL+"/catalog/movie-edition-kinds/{id}", wrapper.DeleteMovieEditionKind)
	m.HandleFunc("GET "+options.BaseURL+"/catalog/movie-edition-kinds/{id}", wrapper.GetMovieEditionKind)
	m.HandleFunc("PATCH "+options.BaseURL+"/catalog/movie-edition-kinds/{id}", wrapper.PatchMovieEditionKind)
	m.HandleFunc("GET "+options.BaseURL+"/inbox/dvd", wrapper.GetInboxDVDs)

	return m
}

type ErrorResponseJSONResponse ErrorResponse

type ListCardsRequestObject struct {
	Params ListCardsParams
}

type ListCardsResponseObject interface {
	VisitListCardsResponse(w http.ResponseWriter) error
}

type ListCards200JSONResponse CardPage

func (response ListCards200JSONResponse) VisitListCardsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCardsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListCardsdefaultJSONResponse) VisitListCardsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostCardRequestObject struct {
	Body *PostCardJSONRequestBody
}

type PostCardResponseObject interface {
	VisitPostCardResponse(w http.ResponseWriter) error
}

type PostCard201JSONResponse Card

func (response PostCard201JSONResponse) VisitPostCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostCarddefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response PostCarddefaultJSONResponse) VisitPostCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteCardRequestObject struct {
	Id uint32 `json:"id"`
}

type DeleteCardResponseObject interface {
	VisitDeleteCardResponse(w http.ResponseWriter) error
}

type DeleteCard204Response struct {
}

func (response DeleteCard204Response) VisitDeleteCardResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCarddefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response DeleteCarddefaultJSONResponse) VisitDeleteCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetCardRequestObject struct {
	Id uint32 `json:"id"`
}

type GetCardResponseObject interface {
	VisitGetCardResponse(w http.ResponseWriter) error
}

type GetCard200JSONResponse Card

func (response GetCard200JSONResponse) VisitGetCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCarddefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetCarddefaultJSONResponse) VisitGetCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PatchCardRequestObject struct {
	Id   uint32 `json:"id"`
	Body *PatchCardJSONRequestBody
}

type PatchCardResponseObject interface {
	VisitPatchCardResponse(w http.ResponseWriter) error
}

type PatchCard200JSONResponse Card

func (response PatchCard200JSONResponse) VisitPatchCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchCarddefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response PatchCarddefaultJSONResponse) VisitPatchCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListMovieEditionKindsRequestObject struct {
	Params ListMovieEditionKindsParams
}

type ListMovieEditionKindsResponseObject interface {
	VisitListMovieEditionKindsResponse(w http.ResponseWriter) error
}

type ListMovieEditionKinds200JSONResponse MovieEditionKindPage

func (response ListMovieEditionKinds200JSONResponse) VisitListMovieEditionKindsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListMovieEditionKindsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListMovieEditionKindsdefaultJSONResponse) VisitListMovieEditionKindsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostMovieEditionKindRequestObject struct {
	Body *PostMovieEditionKindJSONRequestBody
}

type PostMovieEditionKindResponseObject interface {
	VisitPostMovieEditionKindResponse(w http.ResponseWriter) error
}

type PostMovieEditionKind201JSONResponse MovieEditionKind

func (response PostMovieEditionKind201JSONResponse) VisitPostMovieEditionKindResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostMovieEditionKinddefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response PostMovieEditionKinddefaultJSONResponse) VisitPostMovieEditionKindResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteMovieEditionKindRequestObject struct {
	Id uint32 `json:"id"`
}

type DeleteMovieEditionKindResponseObject interface {
	VisitDeleteMovieEditionKindResponse(w http.ResponseWriter) error
}

type DeleteMovieEditionKind204Response struct {
}

func (response DeleteMovieEditionKind204Response) VisitDeleteMovieEditionKindResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteMovieEditionKinddefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response DeleteMovieEditionKinddefaultJSONResponse) VisitDeleteMovieEditionKindResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetMovieEditionKindRequestObject struct {
	Id uint32 `json:"id"`
}

type GetMovieEditionKindResponseObject interface {
	VisitGetMovieEditionKindResponse(w http.ResponseWriter) error
}

type GetMovieEditionKind200JSONResponse MovieEditionKind

func (response GetMovieEditionKind200JSONResponse) VisitGetMovieEditionKindResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMovieEditionKinddefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetMovieEditionKinddefaultJSONResponse) VisitGetMovieEditionKindResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PatchMovieEditionKindRequestObject struct {
	Id   uint32 `json:"id"`
	Body *PatchMovieEditionKindJSONRequestBody
}

type PatchMovieEditionKindResponseObject interface {
	VisitPatchMovieEditionKindResponse(w http.ResponseWriter) error
}

type PatchMovieEditionKind200JSONResponse MovieEditionKind

func (response PatchMovieEditionKind200JSONResponse) VisitPatchMovieEditionKindResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchMovieEditionKinddefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response PatchMovieEditionKinddefaultJSONResponse) VisitPatchMovieEditionKindResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetInboxDVDsRequestObject struct {
	Params GetInboxDVDsParams
}

type GetInboxDVDsResponseObject interface {
	VisitGetInboxDVDsResponse(w http.ResponseWriter) error
}

type GetInboxDVDs200JSONResponse InboxPage

func (response GetInboxDVDs200JSONResponse) VisitGetInboxDVDsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInboxDVDsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetInboxDVDsdefaultJSONResponse) VisitGetInboxDVDsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List cards
	// (GET /catalog/cards)
	ListCards(ctx context.Context, request ListCardsRequestObject) (ListCardsResponseObject, error)
	// Create a new card
	// (POST /catalog/cards)
	PostCard(ctx context.Context, request PostCardRequestObject) (PostCardResponseObject, error)
	// Delete a card
	// (DELETE /catalog/cards/{id})
	DeleteCard(ctx context.Context, request DeleteCardRequestObject) (DeleteCardResponseObject, error)
	// Get a card by ID
	// (GET /catalog/cards/{id})
	GetCard(ctx context.Context, request GetCardRequestObject) (GetCardResponseObject, error)
	// Update a card
	// (PATCH /catalog/cards/{id})
	PatchCard(ctx context.Context, request PatchCardRequestObject) (PatchCardResponseObject, error)
	// List movie edition kinds
	// (GET /catalog/movie-edition-kinds)
	ListMovieEditionKinds(ctx context.Context, request ListMovieEditionKindsRequestObject) (ListMovieEditionKindsResponseObject, error)
	// Create a new movie edition kind
	// (POST /catalog/movie-edition-kinds)
	PostMovieEditionKind(ctx context.Context, request PostMovieEditionKindRequestObject) (PostMovieEditionKindResponseObject, error)
	// Delete a movie edition kind
	// (DELETE /catalog/movie-edition-kinds/{id})
	DeleteMovieEditionKind(ctx context.Context, request DeleteMovieEditionKindRequestObject) (DeleteMovieEditionKindResponseObject, error)
	// Get a movie edition kind by ID
	// (GET /catalog/movie-edition-kinds/{id})
	GetMovieEditionKind(ctx context.Context, request GetMovieEditionKindRequestObject) (GetMovieEditionKindResponseObject, error)
	// Update a movie edition kind
	// (PATCH /catalog/movie-edition-kinds/{id})
	PatchMovieEditionKind(ctx context.Context, request PatchMovieEditionKindRequestObject) (PatchMovieEditionKindResponseObject, error)
	// Get DVDs that have not been ingested to the manager yet.
	// (GET /inbox/dvd)
	GetInboxDVDs(ctx context.Context, request GetInboxDVDsRequestObject) (GetInboxDVDsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListCards operation middleware
func (sh *strictHandler) ListCards(w http.ResponseWriter, r *http.Request, params ListCardsParams) {
	var request ListCardsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCards(ctx, request.(ListCardsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCards")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCardsResponseObject); ok {
		if err := validResponse.VisitListCardsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostCard operation middleware
func (sh *strictHandler) PostCard(w http.ResponseWriter, r *http.Request) {
	var request PostCardRequestObject

	var body PostCardJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostCard(ctx, request.(PostCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostCardResponseObject); ok {
		if err := validResponse.VisitPostCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCard operation middleware
func (sh *strictHandler) DeleteCard(w http.ResponseWriter, r *http.Request, id uint32) {
	var request DeleteCardRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCard(ctx, request.(DeleteCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCardResponseObject); ok {
		if err := validResponse.VisitDeleteCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCard operation middleware
func (sh *strictHandler) GetCard(w http.ResponseWriter, r *http.Request, id uint32) {
	var request GetCardRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCard(ctx, request.(GetCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCardResponseObject); ok {
		if err := validResponse.VisitGetCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchCard operation middleware
func (sh *strictHandler) PatchCard(w http.ResponseWriter, r *http.Request, id uint32) {
	var request PatchCardRequestObject

	request.Id = id

	var body PatchCardJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchCard(ctx, request.(PatchCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchCardResponseObject); ok {
		if err := validResponse.VisitPatchCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMovieEditionKinds operation middleware
func (sh *strictHandler) ListMovieEditionKinds(w http.ResponseWriter, r *http.Request, params ListMovieEditionKindsParams) {
	var request ListMovieEditionKindsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMovieEditionKinds(ctx, request.(ListMovieEditionKindsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMovieEditionKinds")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMovieEditionKindsResponseObject); ok {
		if err := validResponse.VisitListMovieEditionKindsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostMovieEditionKind operation middleware
func (sh *strictHandler) PostMovieEditionKind(w http.ResponseWriter, r *http.Request) {
	var request PostMovieEditionKindRequestObject

	var body PostMovieEditionKindJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostMovieEditionKind(ctx, request.(PostMovieEditionKindRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostMovieEditionKind")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostMovieEditionKindResponseObject); ok {
		if err := validResponse.VisitPostMovieEditionKindResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteMovieEditionKind operation middleware
func (sh *strictHandler) DeleteMovieEditionKind(w http.ResponseWriter, r *http.Request, id uint32) {
	var request DeleteMovieEditionKindRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteMovieEditionKind(ctx, request.(DeleteMovieEditionKindRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteMovieEditionKind")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteMovieEditionKindResponseObject); ok {
		if err := validResponse.VisitDeleteMovieEditionKindResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMovieEditionKind operation middleware
func (sh *strictHandler) GetMovieEditionKind(w http.ResponseWriter, r *http.Request, id uint32) {
	var request GetMovieEditionKindRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMovieEditionKind(ctx, request.(GetMovieEditionKindRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMovieEditionKind")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMovieEditionKindResponseObject); ok {
		if err := validResponse.VisitGetMovieEditionKindResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchMovieEditionKind operation middleware
func (sh *strictHandler) PatchMovieEditionKind(w http.ResponseWriter, r *http.Request, id uint32) {
	var request PatchMovieEditionKindRequestObject

	request.Id = id

	var body PatchMovieEditionKindJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchMovieEditionKind(ctx, request.(PatchMovieEditionKindRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchMovieEditionKind")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchMovieEditionKindResponseObject); ok {
		if err := validResponse.VisitPatchMovieEditionKindResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInboxDVDs operation middleware
func (sh *strictHandler) GetInboxDVDs(w http.ResponseWriter, r *http.Request, params GetInboxDVDsParams) {
	var request GetInboxDVDsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInboxDVDs(ctx, request.(GetInboxDVDsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInboxDVDs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInboxDVDsResponseObject); ok {
		if err := validResponse.VisitGetInboxDVDsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZTW/bOBP+KwO+79G13Q/swbduUwRBN9gg6fZSBAYtjmU2EqmSIzfawP99QVKWrQ87",
	"itdOdrE9NaVGw5l5Zh49pB9YpNNMK1Rk2eSBGbSZVhb9fz4ao811ueIWIq0IFbk/eZYlMuIktRp9s1q5",
	"NRstMOXur/8bnLMJ+99o430UntpR3etqtRowgTYyMnPO2CRsC2ZjMSg9+6A+cCPcv5nRGRqSIVTp1+ba",
	"pJzYhOVS0ds3bMCoyJBNmFSEMRq2GrBULyU+FuOlN1oNmOKpNy79WDJSxe5Bgdz023I1YAa/59KgYJOv",
	"LtLS7W1lq2ffMCLn1mV3xWNsZxhxI0KqhKl9LAFfpVW1ATeGFz4fvKdpxmOckr5D1ZFaI9yw7e5QKVo4",
	"J3UE/TIEU/ghaQFaJQVohTCXmAiwSJChAakscRUhGzSy7Y9SCOFoULXSbA1BI1C0tsRrfyHXhl2lvFAz",
	"fd8N++OADVjGaVFvjZZJvQ8aoYX3uwK7XMNQDwqFdEj3b0fv52N4q6st51xxQ9Mwxa3g+w83pWI27TD/",
	"5V3Pwawy21mNdRZ/g4LupBJPqdgnZ98Zrvf0WKifyu0ODVfaqcA5zxPaQmemdYJc7Rm8nbxX89gn+O7J",
	"8BQxLQGbukoc1o+hukegyq6A+qV3IhI9HLjumE8WKBdi2q7etH+L7ucPg6leYmOH05HKjuJpS+0mFpz4",
	"1OrcRD2/dtrSGSd+E15Z65lm3eqT0CvJfR+I7Shv9yW4FVqrTdwzCE5grg1EBjlJFQMHn8MQ4PdG3yx0",
	"ngiYoeugYatrPC4h/cPRcUtSzXU73uuPN5/h/dVFCFanaa684FVxaHJaIHyRAjVccsVjNDDj0R0q1+9m",
	"KSN0EZOkxG1XN3x/dcEGbInGhq1eD8fDsSukzlDxTLIJe+uXtr7to4gTT3Q8qoRgjL6hXEm8Dr8QbMJ+",
	"k5Y+eAv3ruEpEhrLJl+b6V3ye5nmKag8naEBPQffL0AaDFJulONpZ/g9R1OsuXvCPCNa+aeb4o3g76Ot",
	"mhF8drTqq5vxWCqfw75NAw1v79okrttB/QDzZjw+2rGlUuYdJ5abPIrQ2nmebB1bnFFFvl2eq1BbR6IB",
	"s3maclOUgELA3Em9kkXqoLvR84o/jC1a+lWL4kmpN3o/eIGZFkVzWF0sT57VJ+h5l+GOQd1wEpkcVy20",
	"Xx8V7S6kP7g6oDgausEfcFD4w1fWP6/P+uhBilXAKEHCNvxnfr1sgMbQ+2lyJLIZJrnuk00pnzjK7Tl7",
	"18H3PioBthqOpDha3YLzshud104yPEd60aqMT96Pp2Sec6SywDAr4OKsPGoGCdggILf83KU+jOh6X59U",
	"FwsNadSDh/7duP+RCb41W9t85Gn8VSk2X1Vnrp1KpHnU+alKjtwfnUfll1AovjOg7AwInbFXr7SO4IeP",
	"9LFOvdtHnh03tM+rQjougZ5XkbRRfZQPeqqVDvj/Y8qlq7a7dcw/pl7jZ+3u0+ubNgz91M5LAnJC5dN9",
	"OfnCKuilO6VSRLv4UKqZvh+Jpdiphs6R/K88Z1/OfoqgI7fH5uezfn0xBLj2dbTgr9dchR0uIJW/1fNo",
	"Do/KM949LTjBgi8RlCaYISqQKkbrvjWk/dZpeUNYIA1dNqu/AgAA//8G6vn+oR8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
