// Package vmapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package vmapi

// GetHelloResponse defines model for GetHelloResponse.
type GetHelloResponse struct {
	Message string `json:"message"`
}
