// Package vmapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package vmapi

// HelloResponse defines model for HelloResponse.
type HelloResponse struct {
	Message string `json:"message"`
}
