// Package vmapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package vmapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Card defines model for Card.
type Card struct {
	Id    uint32  `json:"id"`
	Movie *Movie  `json:"movie,omitempty"`
	Name  *string `json:"name,omitempty"`
	Year  *uint32 `json:"year,omitempty"`
}

// CardPatch Patch object with only one field set per instance
type CardPatch struct {
	// Movie Patch object with only one field set per instance
	Movie *MoviePatch `json:"movie,omitempty"`
	Name  *string     `json:"name,omitempty"`
	Year  *uint32     `json:"year,omitempty"`
}

// Movie defines model for Movie.
type Movie struct {
	Editions *[]MovieEdition `json:"editions,omitempty"`
	FanartId *string         `json:"fanart_id,omitempty"`
	Id       uint32          `json:"id"`
	TmdbId   *uint64         `json:"tmdb_id,omitempty"`
}

// MovieEdition defines model for MovieEdition.
type MovieEdition struct {
	Id   uint32           `json:"id"`
	Kind MovieEditionKind `json:"kind"`
}

// MovieEditionKind defines model for MovieEditionKind.
type MovieEditionKind struct {
	Id        uint32 `json:"id"`
	IsDefault bool   `json:"is_default"`
	Name      string `json:"name"`
}

// MovieEditionKindPatch Patch object with only one field set per instance
type MovieEditionKindPatch struct {
	IsDefault *bool   `json:"is_default,omitempty"`
	Name      *string `json:"name,omitempty"`
}

// MoviePatch Patch object with only one field set per instance
type MoviePatch struct {
	AddMovieEditionKindId *uint32 `json:"add_movie_edition_kind_id,omitempty"`
	FanartId              *string `json:"fanart_id,omitempty"`
	RemoveMovieEditionId  *uint32 `json:"remove_movie_edition_id,omitempty"`
	TmdbId                *uint64 `json:"tmdb_id,omitempty"`
}

// MoviePost defines model for MoviePost.
type MoviePost struct {
	// DataSource Data source for creating a movie.  Only one field should be set.
	DataSource          MoviePostDataSource `json:"data_source"`
	MovieEditionKindIds *[]uint32           `json:"movie_edition_kind_ids,omitempty"`
}

// MoviePostDataSource Data source for creating a movie.  Only one field should be set.
type MoviePostDataSource struct {
	TmdbMovieId *uint64 `json:"tmdb_movie_id,omitempty"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7SVQW/TTBCG/8povu9opYUiDr6hwgFVFZVAXFBlTbzjeMHeNbPjoKjKf0e7TmkSp8EE",
	"cmozHs8878y76wcsfdt5x04D5g8YyppbSv9ek5j4txPfsajlFLUpVnlpSTHH3jq9eokZ6qpjzNE65QUL",
	"rjNs/dJyTP5fuMIc/7t4anWx6XNxm5LWGTpqU/KmTlCxbhEfrJhkWst1hsLfeytsMP8SSe9/Jfn5Vy41",
	"1ouy7kjLOhY1HEqxnVrvMMcUhiEVflitwbtmBd4xVJYbA4EVOhawLii5kjHbm850zQPCPxM+knn7SLIL",
	"yMZGscMqldswCfbd8BY+NSIRWsXfFTkSLQZbjDRMd4u2Zl4cSH/96uRN76D/hZG/WWf+ZEw3Mf8A46bS",
	"71BvNu1OxbWhMFxR3+jWSubeN0zuiOEO8abUnYpT4M92uk5Xdpj5bKBkTJGugmJz3oq4+WL6Do+fKuHW",
	"L3mvw/mO2jPD80HHNjWkVATfSznxGvRB35LSx+GVx8/G/tx276tJInfuqT1zb1PeHxO4hTaySXwGQxGo",
	"vEApTGrdAgiShhnAhz3f1L5vDMw5Omg2ck3ayyD/9O3EkHWVH/N+WnUMhivrhk9Agtaa4bM17OGWHC1Y",
	"4JqUGr+AN3fvI6JabWL9Z5Mg1g2Y4ZIlDJ1ezC5nl3GOvmNHncUcr1Iow460Dpi7vmnWPwMAAP//MQMF",
	"inwIAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
