//go:build go1.22

// Package vmserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package vmserver

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/krelinga/video-manager-api/go/vmapi/vmtypes"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ListCardsParams defines parameters for ListCards.
type ListCardsParams struct {
	// PageSize Maximum number of items to return
	PageSize *uint32 `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// PostCardJSONBody defines parameters for PostCard.
type PostCardJSONBody struct {
	Movie *externalRef0.MoviePost `json:"movie,omitempty"`
}

// PatchCardJSONBody defines parameters for PatchCard.
type PatchCardJSONBody = []externalRef0.CardPatch

// ListMovieEditionKindsParams defines parameters for ListMovieEditionKinds.
type ListMovieEditionKindsParams struct {
	// PageSize Maximum number of items to return
	PageSize *uint32 `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// PostMovieEditionKindJSONBody defines parameters for PostMovieEditionKind.
type PostMovieEditionKindJSONBody struct {
	IsDefault *bool   `json:"is_default,omitempty"`
	Name      *string `json:"name,omitempty"`
}

// PatchMovieEditionKindJSONBody defines parameters for PatchMovieEditionKind.
type PatchMovieEditionKindJSONBody = []externalRef0.MovieEditionKindPatch

// PostCardJSONRequestBody defines body for PostCard for application/json ContentType.
type PostCardJSONRequestBody PostCardJSONBody

// PatchCardJSONRequestBody defines body for PatchCard for application/json ContentType.
type PatchCardJSONRequestBody = PatchCardJSONBody

// PostMovieEditionKindJSONRequestBody defines body for PostMovieEditionKind for application/json ContentType.
type PostMovieEditionKindJSONRequestBody PostMovieEditionKindJSONBody

// PatchMovieEditionKindJSONRequestBody defines body for PatchMovieEditionKind for application/json ContentType.
type PatchMovieEditionKindJSONRequestBody = PatchMovieEditionKindJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List cards
	// (GET /cards)
	ListCards(w http.ResponseWriter, r *http.Request, params ListCardsParams)
	// Create a new card
	// (POST /cards)
	PostCard(w http.ResponseWriter, r *http.Request)
	// Delete a card
	// (DELETE /cards/{id})
	DeleteCard(w http.ResponseWriter, r *http.Request, id uint32)
	// Get a card by ID
	// (GET /cards/{id})
	GetCard(w http.ResponseWriter, r *http.Request, id uint32)
	// Update a card
	// (PATCH /cards/{id})
	PatchCard(w http.ResponseWriter, r *http.Request, id uint32)
	// List movie edition kinds
	// (GET /movie-edition-kinds)
	ListMovieEditionKinds(w http.ResponseWriter, r *http.Request, params ListMovieEditionKindsParams)
	// Create a new movie edition kind
	// (POST /movie-edition-kinds)
	PostMovieEditionKind(w http.ResponseWriter, r *http.Request)
	// Delete a movie edition kind
	// (DELETE /movie-edition-kinds/{id})
	DeleteMovieEditionKind(w http.ResponseWriter, r *http.Request, id uint32)
	// Get a movie edition kind by ID
	// (GET /movie-edition-kinds/{id})
	GetMovieEditionKind(w http.ResponseWriter, r *http.Request, id uint32)
	// Update a movie edition kind
	// (PATCH /movie-edition-kinds/{id})
	PatchMovieEditionKind(w http.ResponseWriter, r *http.Request, id uint32)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCards operation middleware
func (siw *ServerInterfaceWrapper) ListCards(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCardsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCards(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCard operation middleware
func (siw *ServerInterfaceWrapper) PostCard(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCard operation middleware
func (siw *ServerInterfaceWrapper) DeleteCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id uint32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCard operation middleware
func (siw *ServerInterfaceWrapper) GetCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id uint32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchCard operation middleware
func (siw *ServerInterfaceWrapper) PatchCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id uint32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchCard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMovieEditionKinds operation middleware
func (siw *ServerInterfaceWrapper) ListMovieEditionKinds(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMovieEditionKindsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMovieEditionKinds(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMovieEditionKind operation middleware
func (siw *ServerInterfaceWrapper) PostMovieEditionKind(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMovieEditionKind(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMovieEditionKind operation middleware
func (siw *ServerInterfaceWrapper) DeleteMovieEditionKind(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id uint32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMovieEditionKind(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMovieEditionKind operation middleware
func (siw *ServerInterfaceWrapper) GetMovieEditionKind(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id uint32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMovieEditionKind(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchMovieEditionKind operation middleware
func (siw *ServerInterfaceWrapper) PatchMovieEditionKind(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id uint32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchMovieEditionKind(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/cards", wrapper.ListCards)
	m.HandleFunc("POST "+options.BaseURL+"/cards", wrapper.PostCard)
	m.HandleFunc("DELETE "+options.BaseURL+"/cards/{id}", wrapper.DeleteCard)
	m.HandleFunc("GET "+options.BaseURL+"/cards/{id}", wrapper.GetCard)
	m.HandleFunc("PATCH "+options.BaseURL+"/cards/{id}", wrapper.PatchCard)
	m.HandleFunc("GET "+options.BaseURL+"/movie-edition-kinds", wrapper.ListMovieEditionKinds)
	m.HandleFunc("POST "+options.BaseURL+"/movie-edition-kinds", wrapper.PostMovieEditionKind)
	m.HandleFunc("DELETE "+options.BaseURL+"/movie-edition-kinds/{id}", wrapper.DeleteMovieEditionKind)
	m.HandleFunc("GET "+options.BaseURL+"/movie-edition-kinds/{id}", wrapper.GetMovieEditionKind)
	m.HandleFunc("PATCH "+options.BaseURL+"/movie-edition-kinds/{id}", wrapper.PatchMovieEditionKind)

	return m
}

type ListCardsRequestObject struct {
	Params ListCardsParams
}

type ListCardsResponseObject interface {
	VisitListCardsResponse(w http.ResponseWriter) error
}

type ListCards200JSONResponse []externalRef0.Card

func (response ListCards200JSONResponse) VisitListCardsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostCardRequestObject struct {
	Body *PostCardJSONRequestBody
}

type PostCardResponseObject interface {
	VisitPostCardResponse(w http.ResponseWriter) error
}

type PostCard201JSONResponse externalRef0.Card

func (response PostCard201JSONResponse) VisitPostCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCardRequestObject struct {
	Id uint32 `json:"id"`
}

type DeleteCardResponseObject interface {
	VisitDeleteCardResponse(w http.ResponseWriter) error
}

type DeleteCard204Response struct {
}

func (response DeleteCard204Response) VisitDeleteCardResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCard404Response struct {
}

func (response DeleteCard404Response) VisitDeleteCardResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetCardRequestObject struct {
	Id uint32 `json:"id"`
}

type GetCardResponseObject interface {
	VisitGetCardResponse(w http.ResponseWriter) error
}

type GetCard200JSONResponse externalRef0.Card

func (response GetCard200JSONResponse) VisitGetCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCard404Response struct {
}

func (response GetCard404Response) VisitGetCardResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PatchCardRequestObject struct {
	Id   uint32 `json:"id"`
	Body *PatchCardJSONRequestBody
}

type PatchCardResponseObject interface {
	VisitPatchCardResponse(w http.ResponseWriter) error
}

type PatchCard200JSONResponse externalRef0.Card

func (response PatchCard200JSONResponse) VisitPatchCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchCard404Response struct {
}

func (response PatchCard404Response) VisitPatchCardResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListMovieEditionKindsRequestObject struct {
	Params ListMovieEditionKindsParams
}

type ListMovieEditionKindsResponseObject interface {
	VisitListMovieEditionKindsResponse(w http.ResponseWriter) error
}

type ListMovieEditionKinds200JSONResponse []externalRef0.MovieEditionKind

func (response ListMovieEditionKinds200JSONResponse) VisitListMovieEditionKindsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostMovieEditionKindRequestObject struct {
	Body *PostMovieEditionKindJSONRequestBody
}

type PostMovieEditionKindResponseObject interface {
	VisitPostMovieEditionKindResponse(w http.ResponseWriter) error
}

type PostMovieEditionKind201JSONResponse externalRef0.MovieEditionKind

func (response PostMovieEditionKind201JSONResponse) VisitPostMovieEditionKindResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteMovieEditionKindRequestObject struct {
	Id uint32 `json:"id"`
}

type DeleteMovieEditionKindResponseObject interface {
	VisitDeleteMovieEditionKindResponse(w http.ResponseWriter) error
}

type DeleteMovieEditionKind204Response struct {
}

func (response DeleteMovieEditionKind204Response) VisitDeleteMovieEditionKindResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteMovieEditionKind404Response struct {
}

func (response DeleteMovieEditionKind404Response) VisitDeleteMovieEditionKindResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetMovieEditionKindRequestObject struct {
	Id uint32 `json:"id"`
}

type GetMovieEditionKindResponseObject interface {
	VisitGetMovieEditionKindResponse(w http.ResponseWriter) error
}

type GetMovieEditionKind200JSONResponse externalRef0.MovieEditionKind

func (response GetMovieEditionKind200JSONResponse) VisitGetMovieEditionKindResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMovieEditionKind404Response struct {
}

func (response GetMovieEditionKind404Response) VisitGetMovieEditionKindResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PatchMovieEditionKindRequestObject struct {
	Id   uint32 `json:"id"`
	Body *PatchMovieEditionKindJSONRequestBody
}

type PatchMovieEditionKindResponseObject interface {
	VisitPatchMovieEditionKindResponse(w http.ResponseWriter) error
}

type PatchMovieEditionKind200JSONResponse externalRef0.MovieEditionKind

func (response PatchMovieEditionKind200JSONResponse) VisitPatchMovieEditionKindResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchMovieEditionKind404Response struct {
}

func (response PatchMovieEditionKind404Response) VisitPatchMovieEditionKindResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List cards
	// (GET /cards)
	ListCards(ctx context.Context, request ListCardsRequestObject) (ListCardsResponseObject, error)
	// Create a new card
	// (POST /cards)
	PostCard(ctx context.Context, request PostCardRequestObject) (PostCardResponseObject, error)
	// Delete a card
	// (DELETE /cards/{id})
	DeleteCard(ctx context.Context, request DeleteCardRequestObject) (DeleteCardResponseObject, error)
	// Get a card by ID
	// (GET /cards/{id})
	GetCard(ctx context.Context, request GetCardRequestObject) (GetCardResponseObject, error)
	// Update a card
	// (PATCH /cards/{id})
	PatchCard(ctx context.Context, request PatchCardRequestObject) (PatchCardResponseObject, error)
	// List movie edition kinds
	// (GET /movie-edition-kinds)
	ListMovieEditionKinds(ctx context.Context, request ListMovieEditionKindsRequestObject) (ListMovieEditionKindsResponseObject, error)
	// Create a new movie edition kind
	// (POST /movie-edition-kinds)
	PostMovieEditionKind(ctx context.Context, request PostMovieEditionKindRequestObject) (PostMovieEditionKindResponseObject, error)
	// Delete a movie edition kind
	// (DELETE /movie-edition-kinds/{id})
	DeleteMovieEditionKind(ctx context.Context, request DeleteMovieEditionKindRequestObject) (DeleteMovieEditionKindResponseObject, error)
	// Get a movie edition kind by ID
	// (GET /movie-edition-kinds/{id})
	GetMovieEditionKind(ctx context.Context, request GetMovieEditionKindRequestObject) (GetMovieEditionKindResponseObject, error)
	// Update a movie edition kind
	// (PATCH /movie-edition-kinds/{id})
	PatchMovieEditionKind(ctx context.Context, request PatchMovieEditionKindRequestObject) (PatchMovieEditionKindResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListCards operation middleware
func (sh *strictHandler) ListCards(w http.ResponseWriter, r *http.Request, params ListCardsParams) {
	var request ListCardsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCards(ctx, request.(ListCardsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCards")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCardsResponseObject); ok {
		if err := validResponse.VisitListCardsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostCard operation middleware
func (sh *strictHandler) PostCard(w http.ResponseWriter, r *http.Request) {
	var request PostCardRequestObject

	var body PostCardJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostCard(ctx, request.(PostCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostCardResponseObject); ok {
		if err := validResponse.VisitPostCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCard operation middleware
func (sh *strictHandler) DeleteCard(w http.ResponseWriter, r *http.Request, id uint32) {
	var request DeleteCardRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCard(ctx, request.(DeleteCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCardResponseObject); ok {
		if err := validResponse.VisitDeleteCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCard operation middleware
func (sh *strictHandler) GetCard(w http.ResponseWriter, r *http.Request, id uint32) {
	var request GetCardRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCard(ctx, request.(GetCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCardResponseObject); ok {
		if err := validResponse.VisitGetCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchCard operation middleware
func (sh *strictHandler) PatchCard(w http.ResponseWriter, r *http.Request, id uint32) {
	var request PatchCardRequestObject

	request.Id = id

	var body PatchCardJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchCard(ctx, request.(PatchCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchCardResponseObject); ok {
		if err := validResponse.VisitPatchCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMovieEditionKinds operation middleware
func (sh *strictHandler) ListMovieEditionKinds(w http.ResponseWriter, r *http.Request, params ListMovieEditionKindsParams) {
	var request ListMovieEditionKindsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMovieEditionKinds(ctx, request.(ListMovieEditionKindsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMovieEditionKinds")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMovieEditionKindsResponseObject); ok {
		if err := validResponse.VisitListMovieEditionKindsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostMovieEditionKind operation middleware
func (sh *strictHandler) PostMovieEditionKind(w http.ResponseWriter, r *http.Request) {
	var request PostMovieEditionKindRequestObject

	var body PostMovieEditionKindJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostMovieEditionKind(ctx, request.(PostMovieEditionKindRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostMovieEditionKind")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostMovieEditionKindResponseObject); ok {
		if err := validResponse.VisitPostMovieEditionKindResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteMovieEditionKind operation middleware
func (sh *strictHandler) DeleteMovieEditionKind(w http.ResponseWriter, r *http.Request, id uint32) {
	var request DeleteMovieEditionKindRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteMovieEditionKind(ctx, request.(DeleteMovieEditionKindRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteMovieEditionKind")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteMovieEditionKindResponseObject); ok {
		if err := validResponse.VisitDeleteMovieEditionKindResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMovieEditionKind operation middleware
func (sh *strictHandler) GetMovieEditionKind(w http.ResponseWriter, r *http.Request, id uint32) {
	var request GetMovieEditionKindRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMovieEditionKind(ctx, request.(GetMovieEditionKindRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMovieEditionKind")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMovieEditionKindResponseObject); ok {
		if err := validResponse.VisitGetMovieEditionKindResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchMovieEditionKind operation middleware
func (sh *strictHandler) PatchMovieEditionKind(w http.ResponseWriter, r *http.Request, id uint32) {
	var request PatchMovieEditionKindRequestObject

	request.Id = id

	var body PatchMovieEditionKindJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchMovieEditionKind(ctx, request.(PatchMovieEditionKindRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchMovieEditionKind")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchMovieEditionKindResponseObject); ok {
		if err := validResponse.VisitPatchMovieEditionKindResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY0W/bthP+Vw78/R7d2G2DodDblhRF0GUrlm4vRWDQ4slmK5EqeXLnBf7fhyPlOJYU",
	"V3LjpBv2ZJs68r777rvjyTcitUVpDRryIrkRPl1gIcNXWpXop2fSKf5VOluiI43hmQ5rmXWFJJGISht6",
	"+UKMwh6RCG0I5+jEeiQKu9TIxv93mIlE/G+8dTiuvY2jq8tguh4JIwvcIBCJ8OS0mfODFUrXz/F6JBx+",
	"rrRDJZIPjPf61sjOPmJKfN42xHeS0gUfrdCnTpekrRGJCMsQN8AXTQuwJl+BNQiZxlyBR4ISHWjjSZoU",
	"xajB1ND4I5AHI+GekC83qHbBotIceEwxYeEHAH8d94qtU+mcXPHvTBrpaBpF04qnv5aoULNph/kPp9+o",
	"gJ0AvkHsn7RRwyl7y7s68Nbn9YP9tnZ9KHTtpwozWeV0J0kza3OUZo8cu1AH050T+4dwtDo8PL59yI8G",
	"Vyo1Da1jWtfklLUw7Z/P/TXnsLBLbHg4XiHupdB6agtXSZJTbyuXDmqe1tO5JHkVN26unyaHu/2tV8A7",
	"Ha0h+rtYr78e7B2ALeHwM4hHQWYdpA4laTMHCSGSE4BfG0pa2CpXMEPW1ElLRyFTkYTD88VL2mS2jfe3",
	"11fv4cd3FwFsIY2cM9jgD2rSgUn3II2CVDrlQRugBcJSK7SQSpK5nTNw0pSz1z/Cg0s+DB2cRQN2IkZi",
	"ic5Hz89PJicTZteWaGSpRSJehqWRKCUtQvDj4JC/zTFojJmRDOpCiUT8rD2dBQve42SBhM6L5EMzykv5",
	"py6qAkxVzNCBzSCIB8iCQ6qc4W7Hhp8rdKtNB0xEKec49fovLu+o1r73dhPBe/sJTSC5ZIpDDPucEtvv",
	"eG32tWvWsC+t8VEoLyYT/kitITSBLFmWuU6Dq/FHHy/G7XkDxoMwQraLaD1qBHlVpSl6n1U5bKAFNfqq",
	"KKRb1RmLKuLzyrpz7GaVSyx4jEWKnn6yajUotobG4ykws2rVLErGMrgmB4+EHOc9ZbntQ+QqXLeS+nxQ",
	"4H1z2c7dGXOCqpGvuAoSDH4JXIXnsSzHN1qtI9s5ErYTeR7W61Q26jMIn+t8q3u9yfiWjoFV1y6J044O",
	"HVAp8LdizcOMe9pl/IslyGxlmrzEQ2r98O7O/vQG6UmjnzySdjrrfiCjb5BqOmG2govz0B82w1mjQfDy",
	"YxN7WCMa2GRv3x3bnfZrfeKflOvfSyXvVA93lNBSn9UTx7Mwcey99puvHf+NAMcdAdqvuw82DnQMm/uH",
	"gxaWw+vzSK+YT3Gxd/whccgl387GvQXacwDoSNe/dBjo4u7+0eC74WXyBEp8uJGhTXq/AeIp6T/6MNH9",
	"r9x3MVg8ljpuh4zOjsam6JabVFcuF4lYEJXJeJzbVOYL6yl5NXk1Eevr9d8BAAD//1UwBoJlGQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "types.yml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
